### ISSUE TITLE
Whisper Error: Invalid file format

### ISSUE THREAD

**Issue by dv0zn3r** [daohoangson/bubby#12]
Sending .m4a file from Voice Memos for transcription results in an error: `"Invalid file format. Supported formats: ['flac', 'm4a', 'mp3', 'mp4', 'mpeg', 'mpga', 'oga', 'ogg', 'wav', 'webm']"`. 

What is the use case for whisper? I've figured sending a voice message results in tts response, but could not for whisper.

**Comment by daohoangson** [comment]
Recording a voice message within the Telegram app should work. Looks like you were uploading a m4a from another app?

**Comment by daohoangson** [comment]
Can you grab the log from SST console or AWS console?

**Comment by daohoangson** [comment]
Looks like the lambda failed a call to Telegram to upload the voice reply. If you send another voice message, it should respond just fine. Maybe I will add some retries to overcome this kind of issue.

**Comment by daohoangson** [comment]
That's weird. Did you setup any kind of firewall? 😳

**Comment by daohoangson** [comment]
Are you deploying to AWS to test it or are you running `pnpm dev` to test it locally?

**Comment by daohoangson** [comment]
I have been testing voice messages frequently in the last few days (prod deployment to AWS) and it hasn't failed, even once. The logic behind transcription and synthesis is quite simple. Without a detailed error stack trace, there is not much we can troubleshoot from here.

**Comment by daohoangson** [comment]
That's possible. Can you ask something that will trigger a short response from the assistant?

**Comment by daohoangson** [comment]
Thanks for the link, I will increase the Telegraf timeout to match the lambda timeout for optimal runtime. Afterwards, it should work better for your bot (with the longer system prompt / assistant response).

**Comment by daohoangson** [comment]
Done 👆
