### ISSUE TITLE
FR: Upgrade Assistants API to v2

### ISSUE THREAD

**Issue by dv0zn3r** [daohoangson/bubby#13]
With the launch of the new model "gpt-4o", it is necessary to upgrade the Assistants API version from v1 to v2 in order to use the new model.

```
Error: 400 The requested model 'gpt-4o' cannot be used with the Assistants API in v1.
```

**Comment by daohoangson** [comment]
Since #14, the Telegram bot will switch to GPT-4o via Assistant API v2. Please try upgrading and let me know whether it works for you.

With this new model, some of the tools will be removed though. Because it is multi modal already.
